version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: postgres_microwave
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2335223352
      POSTGRES_DB: microwave
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: microwave-app:latest
    container_name: microwave_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/microwave
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 2335223352
      SPRING_JPA_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SERVER_PORT: 8081
    depends_on:
      - postgres

volumes:
  postgres_data:
